### ISSUE TITLE
weights in pb or onnx format 

### ISSUE THREAD

**Issue by ak9250** [Onr/Council-GAN#10]
can the weights be exported to a frozen_graph.pb or model.onnx file?

**Comment by ak9250** [comment]
in particular the pretrained anime model

**Comment by ak9250** [comment]
getting this error when exporting ModuleAttributeError: 'Council_Trainer' object has no attribute 'gen_b2a'

**Comment by Onr** [comment]
It is most likely happen because   `load_state_dic` failed. Probably because the defined network doesn't match the saved .pt. it can come from using different config.yaml file then the one used for training and the creation of the .pt file. or maybe using a config for 256 with a saved network for 128.
if you can give me more details i could better figure out what want wrong

**Comment by ak9250** [comment]
@Onr I am using the config from the colab
config = './pretrain/anime/256/anime2face_council_folder.yaml'  #@param {type: "string"}
checkpoint = './pretrain/anime/256/b2a_gen_0_01000000.pt'  #@param {type: "string"}
input_folder = './input_folder'  #@param {type: "string"}
output_folder = './output_folder'  #@param {type: "string"}
output_path = 'outputs' #@param {type: "string"}
a2b = 1 #@param {type: "integer"} #1 for a2b 0 for b2a
seed = 1 #@param {type: "integer"}
num_style = 10 #@param {type: "integer"}
output_only = False #@param{type: "boolean"}
num_of_images_to_test = 100 #@param {type: "integer"}
config = get_config(config)

**Comment by ak9250** [comment]
@Onr still get same error
trainer.eval()
dummy_input = torch.randn(1, 3, 256, 256, 
                          dtype=torch.float32, device=DEVICE)

output = trainer(dummy_input.detach())

input_names = ['data']
output_names = ['output1']

torch.onnx.export(trainer, dummy_input, 
                  ONNX_PATH, verbose=False, 
                  input_names=input_names, output_names=output_names)

**Comment by Onr** [comment]
I failed to export to onnx. i fixed some issues with the code to better work with onnx. and tried to export part of the network the encoder works fine but the decoder don't. I think i narrowed the problem to the implementation of AdaIn, but i wast able to fix it.
 I attached the script tried to run. if you try it you should pull the latest version of this repository first.
[onnx_export.py.zip](https://github.com/Onr/Council-GAN/files/5063948/onnx_export.py.zip)

**Comment by ak9250** [comment]
@Onr ok i will take a look at it, was there a error for the export part?

**Comment by Onr** [comment]
@ak9250 no it export without any errors.
you can run onnx_export.py with: 
`python convert_to_onnx.py --config pretrain/anime/128/anime2face_council_folder.yaml --checkpoint pretrain/anime/128/01000000 --input_folder ./datasets/selfie2anime/testB --a2b 0`

**Comment by ak9250** [comment]
@Onr ok could you also please provide the onnx file you exported?

**Comment by ak9250** [comment]
@Onr I get this error in colab for !python onnx_export.py --config /content/Council-GAN/configs/anime2face_council_folder.yaml --checkpoint /content/Council-GAN/pretrain/anime/128/b2a_gen_0_01000000.pt --input_folder ./datasets/selfie2anime/testB --a2b 0

https://github.com/computationalmedia/semstyle/issues/3

**Comment by Onr** [comment]
@ak9250 Sure 
the onnx file is too big to attach here is a link
https://drive.google.com/file/d/16GrAGfkWxVwtWqLyOomRc_-6ZsGThRei/view?usp=sharing

as for the error try with this:
[onnx_export.py.zip](https://github.com/Onr/Council-GAN/files/5065685/onnx_export.py.zip)

**Comment by ak9250** [comment]
@Onr thanks it says i need access for the google drive file

**Comment by Onr** [comment]
i think it should work now
 https://drive.google.com/file/d/16GrAGfkWxVwtWqLyOomRc_-6ZsGThRei/view?usp=sharing

**Comment by ak9250** [comment]
@Onr have you looked at model compression for gans like https://github.com/mit-han-lab/gan-compression
I thought the model would be smaller since one of the checkpoints was around 20 mb

**Comment by Onr** [comment]
@ak9250 thanks. ill look into it
