### ISSUE TITLE
Focus_loss ?

### ISSUE THREAD

**Issue by roger-cv** [Onr/Council-GAN#12]
Hey, thanks for the code.

What part of the code is Focus_loss in? Would you please explain "the value of the 4th channel for pixel k"?

**Comment by Onr** [comment]
Hey Roger
the Focus_loss is in the trainer_council.py search for "focus_loss" and you will find all of its parts.
you can also look in networks.py at Decoder_V2_atten to see how the masks is being used.
here is an illustration of how the  4th channel is used.
![mask](https://user-images.githubusercontent.com/8344672/102893602-898eee80-446a-11eb-8c5d-beddf05e9a57.png)

**Comment by roger-cv** [comment]
Thanks for you reply.
