### ISSUE TITLE
pretrained model loading error

### ISSUE THREAD

**Issue by arufus** [Onr/Council-GAN#2]
I downloaded pretrained selfie to anime model,  

when using `python test_on_folder.py`, in `trainer.gen_b2a_s[i].load_state_dict(state_dict['b2a'])`, I got an error, it says:

{RuntimeError}Error(s) in loading state_dict for AdaINGen:
	Missing key(s) in state_dict: "enc_content.model.2.conv.weight", "enc_content.model.2.conv.bias", "enc_content.model.3.model.0.model.0.conv.weight", "enc_content.model.3.model.0.model.0.conv.bias", "enc_content.model.3.model.0.model.1.conv.weight", "enc_content.model.3.model.0.model.1.conv.bias", "enc_content.model.3.model.1.model.0.conv.weight", "enc_content.model.3.model.1.model.0.conv.bias", "enc_content.model.3.model.1.model.1.conv.weight", "enc_content.model.3.model.1.model.1.conv.bias", "enc_content.model.3.model.2.model.0.conv.weight", "enc_content.model.3.model.2.model.0.conv.bias", "enc_content.model.3.model.2.model.1.conv.weight", "enc_content.model.3.model.2.model.1.conv.bias", "enc_content.model.3.model.3.model.0.conv.weight", "enc_content.model.3.model.3.model.0.conv.bias", "enc_content.model.3.model.3.model.1.conv.weight", "enc_content.model.3.model.3.model.1.conv.bias", "enc_content.model.3.model.4.model.0.conv.weight", "enc_...

**Comment by Onr** [comment]
try running:
`python test_on_folder.py --config pretrain/anime/256/anime2face_council_folder.yaml --output_folder outputs/council_anime2face_256_256 --checkpoint pretrain/anime/256/01000000 --input_folder ./datasets/selfie2anime/testB --a2b 0`
or:
`python test_on_folder.py --config pretrain/anime/128/anime2face_council_folder.yaml --output_folder outputs/council_anime2face_128_128 --checkpoint pretrain/anime/128/01000000 --input_folder ./datasets/selfie2anime/testB --a2b 0`

maybe you are using config.yaml file for size 128 with network for 256

**Comment by arufus** [comment]
@Onr, Problem solved, Thanks a lot! I didn't notice that there is a .yaml file in the folder containing the ckpt file. Amazing work!
