### ISSUE TITLE
Is the default max_iter too big?

### ISSUE THREAD

**Issue by zgxiangyang** [Onr/Council-GAN#7]
In the default config file ,max_iter is set to 1_500_000, while it is 100_000 in you paper.

**Comment by Onr** [comment]
it is just so it won't stop before you want it to, and you can look at what more iteration will produce.
and we trained the networked until 1_000_000 as in MUNIT

**Comment by zgxiangyang** [comment]
How long did it take to run for 1_000_000 iterations.

**Comment by Onr** [comment]
hey @zgxiangyang sorry for the delay it took about two weeks
