### ISSUE TITLE
Female to male translation

### ISSUE THREAD

**Issue by Nerdyvedi** [Onr/Council-GAN#8]
Hi,
Thank you so much for uploading such a great work.

Could you upload the pretrained weights for female to male translation as well.
Thanks

**Comment by Onr** [comment]
Hi @Nerdyvedi 
The weights should be available with the command:
`bash scripts/download.sh pretrain_male_to_female`
or you could download them from:
[pretrain_male_to_female](https://onedrive.live.com/download?cid=552378614E6BA583&resid=552378614E6BA583%2119549&authkey=ANzlMZsBQy77urU)
